os: linux
dist: xenial
language: node_js
node_js: lts/*

# SSH Setup
addons:
  ssh_known_hosts: tygr.info

script:
  - npm run quality:check
  - NODE_ENV=production npm run build

deploy:
  - provider: npm
    on:
      branch: main
      tags: true
      repo: tylergrinn/tygr-tabs
    edge: true
    email: tylergrinn@gmail.com
    api_token: $NPM_TOKEN

  - provider: script
    on:
      branch: main
      repo: tylergrinn/tygr-tabs
    edge: true
    script: bash deploy.sh
